### ISSUE TITLE
Change font

### ISSUE THREAD

**Issue by ghost** [mcpcpc/xdate#2]
hello again, how can I change the font of the bar ?, for example to Dejavu

**Comment by mcpcpc** [comment]
Hi Ricardo,

xbar uses the X core font system, XLFD. Take a look at the following Arch wiki page for some good examples of how to find and select an appropriate font string: 

https://wiki.archlinux.org/index.php/X_Logical_Font_Description.

You can the set the desired font in the config.h file.

-mcpcpc
